# Generated by Django 4.1.1 on 2022-09-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_alter_article_options_tag_scope_articl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
    ]
